# Generated by Django 2.0.1 on 2018-02-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_auto_20180217_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSkillLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SEEKING', 'Seeking'), ('NOVICE', 'Novice'), ('TRAINED', 'Trained'), ('EXPERT', 'Expert'), ('MASTER', 'Master')], default='NO', max_length=15)),
                ('created_date', models.DateField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_member', to='opportunities.Member')),
            ],
        ),
        migrations.RenameField(
            model_name='element',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AlterField(
            model_name='skillrecommendation',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.MemberSkillLink'),
        ),
        migrations.AddField(
            model_name='memberskilllink',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_skill', to='opportunities.Skill'),
        ),
    ]
