# Generated by Django 2.0.1 on 2018-02-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_auto_20180217_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(default='images/opportunity_images/nothing.jpg', upload_to='images/opportunity_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, default='images/skill_images/nothing.jpg', null=True, upload_to='images/skill_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, default='images/tag_images/nothing.jpg', null=True, upload_to='images/tag_images/%Y/%m/%d/%H_%M_%S'),
        ),
    ]
