# Generated by Django 2.0.1 on 2018-02-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_auto_20180218_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(default=69512, max_length=255, unique=True),
        ),
    ]
