# Generated by Django 2.0.1 on 2018-02-19 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_application_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='files',
        ),
        migrations.AddField(
            model_name='response',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.File'),
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(default=45727, max_length=255, unique=True),
        ),
    ]
