# Generated by Django 2.0.1 on 2018-02-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_auto_20180219_0228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberSkillLink',
            new_name='LinkedSkill',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='GenericSkill',
        ),
        migrations.AlterField(
            model_name='linkedskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_skill', to='opportunities.GenericSkill'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='images/user_images/nothing.jpg', upload_to='opportunities/static/opportunities/images/user_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(default='opportunities/static/opportunities/images/opportunity_images/nothing.jpg', upload_to='opportunities/static/opportunities/images/opportunity_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, default='opportunities/static/opportunities/images/tag_images/nothing.jpg', null=True, upload_to='opportunities/static/opportunities/images/tag_images/%Y/%m/%d/%H_%M_%S'),
        ),
    ]
