# Generated by Django 2.0.1 on 2018-02-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_auto_20180219_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opportunities.Application'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericskill',
            name='image',
            field=models.ImageField(blank=True, default='opportunities/static/opportunities/images/skill_images/nothing.jpg', null=True, upload_to='opportunities/static/opportunities/images/skill_images/%Y/%m/%d/%H_%M_%S'),
        ),
    ]
