# Generated by Django 2.0.1 on 2018-02-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0010_auto_20180219_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessor',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='requirement',
        ),
        migrations.AddField(
            model_name='response',
            name='assessed_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='response',
            name='assessment',
            field=models.CharField(choices=[('MEETS', 'Meets requirement'), ('FAILS', 'Does not meet requirement'), ('EXCEEDS', 'Exceeds requirement')], default='ME', max_length=32),
        ),
        migrations.AddField(
            model_name='response',
            name='assessor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessing_member', to='opportunities.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='rationale',
            field=models.TextField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applying_member', to='opportunities.Member'),
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
