# Generated by Django 2.0.1 on 2018-02-19 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0011_auto_20180219_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.CharField(choices=[('SEEKING', 'Seeking'), ('NOVICE', 'Novice'), ('TRAINED', 'Trained'), ('EXPERT', 'Expert'), ('MASTER', 'Master')], default='NO', max_length=15)),
                ('created_date', models.DateField(auto_now=True)),
                ('Opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_opportunity', to='opportunities.Opportunity')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skill', to='opportunities.GenericSkill')),
            ],
        ),
    ]
