# Generated by Django 2.0.1 on 2018-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0012_requiredskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='req_type',
            field=models.CharField(choices=[('QUESTION', 'Question'), ('DEMOGRAPHIC', 'Demographic'), ('EDUCATION', 'Education'), ('CERTIFICATION', 'Certification'), ('TRAINING', 'Training'), ('EXPERIENCE', 'Experience'), ('BEHAVIOR', 'Behavior')], default='EX', max_length=32),
        ),
    ]
