# Generated by Django 2.0.1 on 2018-02-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0013_auto_20180219_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requiredskill',
            old_name='Opportunity',
            new_name='opportunity',
        ),
    ]
