# Generated by Django 2.0.1 on 2018-02-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0014_auto_20180219_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredskill',
            name='description',
            field=models.TextField(blank=True, default='Enter description here', max_length=250),
        ),
    ]
