# Generated by Django 2.0.1 on 2018-02-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0015_requiredskill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='evidence',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='response',
            name='rationale',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
