# Generated by Django 2.0.1 on 2018-02-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0016_auto_20180219_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENED_IN', 'Screened In'), ('SCREENED_OUT', 'Screened Out'), ('REVIEW', 'Under Review'), ('ASSESSED', 'Assessment Completed'), ('RETAINED', 'Application Retained'), ('INTERVIEW', 'Interview Requested'), ('OFFERED', 'Job Offered'), ('REFUSED', 'Job Refused'), ('ACCEPTED', 'Job Accepted')], default='Applied', max_length=32),
        ),
        migrations.AlterField(
            model_name='response',
            name='assessment',
            field=models.CharField(choices=[('UNASSESSED', 'Not Assessed'), ('MEETS', 'Meets requirement'), ('FAILS', 'Does not meet requirement'), ('EXCEEDS', 'Exceeds requirement')], default='UN', max_length=32),
        ),
    ]
